config/routes.rb
Rails.application.routes.draw do

  resources :cocktails do
    resources :doses, only: [ :new, :create, :destroy ]
  end

  root :to => 'cocktails#index'

  # get 'doses/index'
  # get 'doses/show'
  # get 'doses/new'
  # get 'doses/edit'

  # get 'cocktails/index'
  # get 'cocktails/show'
  # get 'cocktails/new'
  # get 'cocktails/edit'

end

# RESTAURANTS -----------------------------------------------------
#
  # get 'restaurants', to: 'restaurants#index'

  # get 'restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
  # post 'restaurants', to: 'restaurants#create'

  # get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'

  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant'
  # patch 'restaurants/:id', to: 'restaurants#update'

  # delete 'restaurants/delete', to: 'restaurants#destroy'


# REVIEWS ------------------------------------------------------------
#
  # get 'reviews/index'
  # get 'reviews/show'

  # get 'reviews/new', to: 'reviews#new'
  # get 'reviews', to: 'reviews#create', as: 'review'

  # get 'reviews/update'
  # get 'reviews/edit'

  # get 'reviews/delete'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses


end

app/models/dose.rb
class Dose < ApplicationRecord

  validates :description, presence: true
  # validates_associated :cocktail
  # validates_associated :ingredient

  validates :cocktail, uniqueness: { scope: :ingredient }

  belongs_to :cocktail
  belongs_to :ingredient

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses
  # dependent: :destroy
  # :dependent => :restrict_with_error
  #
  # SMART METHOD TO MAKE SURE YOU DON'T DELETE THE KIDS
  has_many :cocktails, through: :doses
  # before_destroy :check_for_doses

private

  # def check_for_doses
  #   if doses.count > 0
  #     errors.add_to_base("cannot delete ingredients while doses exist")
  #     return false
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

# READ ------I.S------------------------------------

  # GET
  # /cocktails
  def index
    @cocktails = Cocktail.all
  end

  # GET
  # /cocktails/:id
  def show
    @cocktail = Cocktail.find(params[:id])
  end

# CREATE -----N.C-------------------------------------

  def new
    @cocktail = Cocktail.new
  end

  def create

    @cocktail = Cocktail.new(params.require(:cocktail).permit(:name))
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

# UPDATE  ------U.E------------------------------------
  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(params.require(:cocktail).permit(:name, :dose_id))
    redirect_to cocktail_path(@cocktail)
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

# DELETE --------D----------------------------------
  def destroy
    @cocktail = Restaurant.find(params[:id])
    @cocktail.delete
    redirect_to cocktail_path(@cocktail)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController


# CREATE -----N.C-------------------------------------

# -- PREFEX: ---------
# new_cocktail_dose GET

# -- VERB: -----------
# URI PATTERN:

# -- URI PATTERN: ----
# cocktails/1/doses/new

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

# THEN GO TO VIEW ----------------------------------

# -- PREFEX: ---------
# cocktail_dose POST

# -- VERB: -----------
# URI PATTERN:

# -- URI PATTERN: ----
# cocktails/1/doses
  def create



    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(params.require(:dose).permit(:description, :ingredient_id))
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end

  end

# DELETE --------D----------------------------------

# -- PREFEX: ---------
# cocktail_dose

# -- VERB: -----------
# DELETE

# -- URI PATTERN: ----
# cocktails/1/doses/1

  def destroy
    @dose = Restaurant.find(params[:id])

    if @dose.delete
      redirect_to dose_path(@cocktail)
    else
      render :new
    end

  end

# READ ------I.S------------------------------------
  # def index
  #   @doses = Dose.all
  # end

  # def show
  #   @dose = Dose.find(params[id])
  # end

# # UPDATE  ------U.E------------------------------------
#   def update
#     @does = Does.find(params[:id])
#     @does.update(params.require(:dose).permit(:description, :cocktail_id, :does_id))
#     redirect_to does_path(@does)
#   end

#   def edit
#     @does = Does.find(params[:id])
#     @does.save
#     redirect_to does_path(@cocktail)
#   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://download.hipwallpaper.com/desktop/1920/1080/84/87/yxPqfA.jpg');">
  <div class="banner-content">
    <h1>Cocktails</h1>
    <p>Cocktail: Edit Page</p>
    <%= link_to 'Add New Cocktail', new_cocktail_path, class: "btn btn-info" %>
  </div>
</div>

<div class="container">
  <div class="row">

    <ul>
      <li>
        <%= link_to 'Add New Cocktail', new_cocktail_path, class: "btn btn-info" %>
      </li>
      <li>
        <%= link_to 'Back', cocktails_path, class: "btn btn-default" %>
      </li>
    </ul>

  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://scontent.fjog1-1.fna.fbcdn.net/v/t1.0-9/44654972_2176241142614711_3454897278022582272_o.jpg?_nc_cat=111&_nc_ht=scontent.fjog1-1.fna&oh=1c6486a49ec8838b734f4516a367863e&oe=5C745B74');">
  <!-- https://scontent.fjog1-1.fna.fbcdn.net/v/t1.0-9/44654972_2176241142614711_3454897278022582272_o.jpg?_nc_cat=111&_nc_ht=scontent.fjog1-1.fna&oh=1c6486a49ec8838b734f4516a367863e&oe=5C745B74 -->
<!-- https://2.bp.blogspot.com/-hBSUZrju4Bw/W8hwc4hISzI/AAAAAAAAVQg/kM6EJ-xf6r4hyQGmFbUC2TtzjV0P0qXvACEwYBhgL/s640/73566413-B30C-4D9E-8789-3605283D684F.JPG -->

  <div class="banner-content">
    <h1>Blackcat</h1>
    <p>minimart</p>
    <%= link_to 'Add New Cocktail', new_cocktail_path, class: "btn btn-default" %>
  </div>
</div>

<div class="container">
  <div class="row text-center">

  <ul>
    <% @cocktails.each do |cocktail| %>

      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://cdn-image.foodandwine.com/sites/default/files/styles/medium_2x/public/cocktails0615-xl-blood-and-sand.jpg');">
          <!-- <div class="card-category">Popular</div> -->
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
            <p>tastes great</p>
          </div>
          <img class="card-user" src="https://cdn-image.foodandwine.com/sites/default/files/styles/medium_2x/public/cocktails0615-xl-blood-and-sand.jpg">
          <!-- <a class="card-link" href="#" ></a> -->


        </div>
      <%= link_to 'see cocktail', cocktail_path(cocktail), class: "btn btn-default" %>
      </div>



    <% end %>
  </ul>


  </div>
</div>

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://download.hipwallpaper.com/desktop/1920/1080/84/87/yxPqfA.jpg');">
  <div class="banner-content">
    <h1>Create Cocktail</h1>
    <p>Select below</p>
    <%= link_to 'Back', cocktails_path, class: "btn btn-default" %>
  </div>
</div>

<div class="container">
  <div class="row">

    <ul>
      <li>
      <p>Name of the cocktail</p>

        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.button :submit, class: "btn btn-default" %>
        <% end %>

      </li>
      <li>
        <%= link_to 'Back', cocktails_path, class: "btn btn-default" %>
      </li>
    </ul>

  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner banner-half-view" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://download.hipwallpaper.com/desktop/1920/1080/84/87/yxPqfA.jpg');">
  <div class="banner-content">
    <h1><%= @cocktail.name%></h1>
    <p>read more below</p>
<!--     <%= link_to 'Add New Cocktail', new_cocktail_path, class: "btn btn-info" %> -->
  </div>
</div>

<div class="container">
  <div class="row">

    <h3><%= @cocktail.name%></h3>
    <p>Hi I'm a cocktail description</p>

<!-- cocktails/1/doses/new -->

    <%= link_to 'Back', cocktails_path, class: "btn btn-default" %>

    <%= link_to 'Add ingredient', new_cocktail_dose_path(@cocktail), class: "btn btn-default" %>

    <%= cl_image_tag("fwxx5ibghiq7yc0fpcn1") %>

  <!-- app/views/articles/_form.html.erb -->
  <%= simple_form_for(@cocktail) do |f| %>
    <!-- [...] -->
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <!-- [...] -->
  <% end %>

  <!-- app/views/articles/show.html.erb -->
  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>


<!-- https://res.cloudinary.com/jferreira/image/upload/v1541494974/fwxx5ibghiq7yc0fpcn1.jpg -->

  </div>
</div>

app/views/doses/edit.html.erb
<div class="container">
  <div class="row">

  <h1>Does: Edit Page</h1>

  <%= link_to 'Back', doses_path, class: "btn btn-default" %>

  <!-- app/views/articles/_form.html.erb -->
  <%= simple_form_for(@cocktail) do |f| %>
    <!-- [...] -->
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <!-- [...] -->
  <% end %>

  </div>
</div>

app/views/doses/index.html.erb
<div class="container">
  <div class="row">

  <h1>Does: All Page</h1>

  <%= link_to 'Back', doses_path, class: "btn btn-default" %>

  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">

  <h1>Does: New Page</h1>
<!-- create a form to add a dose to a cocktail -->
<!-- < link_to 'Back', doses_path, class: "btn btn-default" %> -->


<!-- 0 - after createing the new fuction in the controller -->
<!-- 1 - need a form, to capture the [ DESCRIPTION ] & [ INGREDEIENT ] take the parent id [ Cocktail ] and the empty [ DOSE ] instance -->
<!-- 2 - sumbit  -->

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, collection: Ingredient.all %>
    <%= f.button :submit %>
  <% end %>


  </div>
</div>

app/views/doses/show.html.erb
<div class="container">
  <div class="row">

  <h1>Does: Show Page</h1>

  <%= link_to 'Back', doses_path, class: "btn btn-default" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
<!--     <%= javascript_include_tag 'application' %> -->

  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %>
    <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
    <!-- from app/javascript/packs/application.js -->
  </body>
</html>